import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-background min-h-screen">
          <div className="container max-w-screen-lg mx-auto px-4 py-8">
            <Navbar />
              {children}
          </div>
        </div>
      </body>
    </html>
  );
}
